# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='bbm.Pins')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbm.Pins')),
            ],
        ),
    ]
